#
title: USM COS 460 Computer Networks
theme: minima
excerpt_separator: <!--more-->
github_username: usm-cos460
author: Stephen Houser
email: houser@maine.edu
description: >-
  University of Southern Maine, 
  Computer Science
future: false

collections:
  notes:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "notes"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
